### PR TITLE
Surveys multiple select

### PR DESCRIPTION
**Pull request by donni106**
feat(surveys): allow multiple responses

- added new flag for questions to be able to allow multiple responses
- added ability to edit that flag per GraphQL like question title
- updated graphql schema

feat(survey votes): add multiple simultaneously increases or decreases 

- added ability to pass arrays as increase id or decrease id
  - passing just an `ID` still works
- adjusted status output to respect just the processed ids and not the requested ones, as there can be passed not existing ones
- fixed typos where `reponse` -> `response`
- added specs for new cases

SVA-361

---

everything is possible now:

```
{
  "increaseId": [113, 115],
  "decreaseId": 114
}

{
  "increaseId": 113,
  "decreaseId": 114
}

{
  "increaseId": [113],
  "decreaseId": [114, 115]
}

{
  "increaseId": [113]
}


{
  "increaseId": 113
}


{
  "increaseId": [113],
  "decreaseId": []
}

{
  "increaseId": [],
  "decreaseId": [113]
}
```

### CODE REVIEW

**Comment by digorath** [comment]
⚠️ bitte noch nicht mergen! irgendwas ist dort noch nicht richtig bzgl. abwärtskompatibilität

Screenshot 2021-11-25 at 15 07 17

**Comment by donni106** [comment]
> ⚠️ please do not merge yet. there are still some issues with backward compatability
> 
> Screenshot 2021-11-25 at 15 07 17

@digorath muss in der query von ID zu [ID!] werden. damit gehts mit insomnia z.b.

**Comment by digorath** [comment]
> > ⚠️ please do not merge yet. there are still some issues with backward compatability
> 
> > 
> 
> > Screenshot 2021-11-25 at 15 07 17
> 
> 
> 
> @digorath muss in der mutation von ID zu [ID!] werden. damit gehts mit insomnia z.b.
> 
> 
> 
> ```
> 
> mutation voteForSurvey($increaseId: [ID!], $decreaseId: [ID!]) {
> 
>   voteForSurvey(increaseId: $increaseId, decreaseId: $decreaseId) {
> 
>     id
> 
>     status
> 
>     statusCode
> 
>   }
> 
> }
> 
> ```
but old apps will not do that automatically!

**Comment by donni106** [comment]
> but old apps will not do that automatically!

thought of the same in the kitchen right now. i will provide a `votesForSurvey...` with the new stuff and deprecate the old one. so we have both for a while

**Comment by donni106** [comment]
done
Bildschirmfoto 2021-11-25 um 15 58 31
Bildschirmfoto 2021-11-25 um 15 58 59
Bildschirmfoto 2021-11-25 um 16 03 34
Bildschirmfoto 2021-11-25 um 16 04 58

**Pull request merged**
